---
title: "History Browser"
author: "Lukasz A. Bartnik"
date: "May 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

Recent development in the R community can be grouped as follows:
extending and simplifying the programming interfaces (tidyverse)
support for big data sets (e.g. interfaces to Spark)
new algorithms to model interactions in data
reproducible programming

This paper explores a direction that to some extent overlaps with the
last category: bookkeeping (recording user interactions and their
results) and reporting (presenting the historical records back to the
user) in a data project and.

It starts with the premise that a considerable amount of time and effort
in a data project is utilized on recording and browsing findings.

The reproducible programming movement produced tools extremely useful
when findings are to be reported for the sake of consumers other than
the user who produced them in the first place.

There seems to be a certain lack of tools, however, that server the
purpose of reducing the operational burder on the researcher himself.

It is important to note that in a project spanning over days or weeks,
the task of reconstructing the context of certain questions stated and
results obtained in a data project is not trivial and at least requires
consideration and time.

We also start with the premise that the most important aspect of any data
project takes place in the mind of the researcher and takes the form of
a narrative about the data: interactions and patterns present in the data,
explanations of those patterns and interactions and ways of modelling them
for the sake of predictions or forecasts.

A researcher needs expected to maintain a record of his thoughts and ideas
that can but doesn't have to reside together with the code and data.

Typically, tools designed for other use cases are repurposed for this task:
markdown notebooks, scripts with comments, sets of plots written to the
filesystem, PDF reports, etc.

Although these tools perform very well when it comes to reporting, using
them to bootstrap another day of work is less straightforward: one needs
to locate objects (data, plots) and code relevant to their ongoing work
and then use them (collect, copy, re-run) as the starting point for the
current part of the project.

R has the basic support for bookkeeping: stores the history of commands,
preserves the state of the session, implements serialization and deserialization
of arbitrary objects (code, data, plots) in the filesystem. The meta level,
however, that has to do with the relationships between these objects,
as well as their relative importance are not recorded by these mechanisms.

The R user is expected to do that work - maintain a comprehensive view
and understanding of the artifacts produced within the project - on their
own.

This is where our package aims: at supporting the user in the task of
recording, browsing and presenting the information about artifacts,
the network of relationships between them and from this, the overall
narrative about the understanding and applicability of the knowledge
obtained in said project.


## Supporting data exploration in R


